#details of sets. Just like Mathmatics only contain unique values and does not repeat value.
s = set()

s.add(50)
s.add(5)
s.add(7)
s.add(9)
s.add(11)
s.add(3)
s.add(1)
s.add(0)
print(s)
s.remove(0)
print(s)
print(f"the set has {len(s)} Unique elements.")